Fix issue with STM32duino Core and I2C address setting
simondlevy/VL53L5 pull request #12
Opened 2021-11-09 09:58 UTC by cparata

Hi all,
here you can find the fix to make the library working also with STM32duino Core and also to fix the I2C address management. Best Regards,
Carlo

2021-11-25 16:14 UTC, fpistm requested changes

2021-11-25 16:14 UTC, fpistm commented on src/st/platform.cpp
> +            byte current_read_size = (size - i > DEFAULT_I2C_BUFFER_LEN ? DEFAULT_I2C_BUFFER_LEN : size - i);
```suggestion
            size_t current_read_size = (size - i > DEFAULT_I2C_BUFFER_LEN ? DEFAULT_I2C_BUFFER_LEN : size - i);
```

2022-11-30 00:40 UTC, simondlevy approved these changes

2022-11-30 01:36 UTC, simondlevy commented
Now that there is a separate [library ](https://github.com/stm32duino/VL53L5CX)for stm32duino, I am closing this issue.

2022-11-30 01:36 UTC, closed without merging

2022-12-05 09:04 UTC, fpistm commented
> Now that there is a separate [library ](https://github.com/stm32duino/VL53L5CX)for stm32duino, I am closing this issue.

Hi @simondlevy 
I think you should consider this even if we provide on our side an other library. Moreover, it provides some fixes I guess which would be useful.